[package]
name = "hir"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hir-def.workspace = true
hir-ty.workspace = true
base-db.workspace = true
bsl-config.workspace = true
bsl-metadata.workspace = true
bsl-platform.workspace = true
bsl-types.workspace = true
syntax.workspace = true
vfs.workspace = true
stdx.workspace = true
rustc-hash.workspace = true
tracing.workspace = true
cfg.workspace = true
dataflow.workspace = true

[dev-dependencies]
expect-test.workspace = true
ide-db.workspace = true
base-db.workspace = true
parser.workspace = true

[lints]
workspace = true
