[package]
name = "ide-host-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
ide.workspace = true
ide-db.workspace = true
base-db.workspace = true
bsl-conventions.workspace = true
bsl-metadata.workspace = true
vfs.workspace = true
rayon.workspace = true
salsa.workspace = true
tracing.workspace = true
project-model.workspace = true
blake3 = "1.8"
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
