[package]
name = "vfs-notify"
version = "0.1.28"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "VFS loader with file watching for bsl-analyzer"

[lib]
doctest = false

[dependencies]
tracing.workspace = true
walkdir.workspace = true
crossbeam-channel.workspace = true
notify.workspace = true
rustc-hash.workspace = true

stdx.workspace = true
vfs.workspace = true
paths.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
