[package]
name = "ide-diagnostics"
version.workspace = true
edition.workspace = true
license = "LGPL-3.0-or-later"
rust-version.workspace = true

[dependencies]
bsl-conventions.workspace = true
base-db.workspace = true
ide-db.workspace = true
intern.workspace = true
lexer.workspace = true
salsa.workspace = true
hir.workspace = true
syntax.workspace = true
parser.workspace = true
sdbl-hir.workspace = true
rustc-hash.workspace = true
vfs.workspace = true
stdx.workspace = true
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
bsl-config.workspace = true
bsl-metadata.workspace = true
bsl-platform.workspace = true
tracing.workspace = true
regex.workspace = true
once_cell.workspace = true
smol_str.workspace = true
line-index.workspace = true
fixedbitset.workspace = true
strum.workspace = true
spellbook.workspace = true
text-size.workspace = true

[dev-dependencies]
tempfile.workspace = true
expect-test.workspace = true
test-fixture.workspace = true
uuid = { version = "1.0", features = ["v4"] }

[lints]
workspace = true
