[package]
name = "test-fixture"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ide-db.workspace = true
base-db.workspace = true
syntax.workspace = true
vfs.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
