//! Generates the EDT global catalog from `data/global_catalog.json` and checks
//! it against its attested counts. The platform help corpus is not part of the
//! build: it is loaded at runtime from a configured source.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let crate_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let global_catalog_path = crate_root.join("data/global_catalog.json");
    println!("cargo:rerun-if-changed=data/global_catalog.json");

    let mut code = String::from(
        "// Auto-generated by build.rs\n// DO NOT EDIT MANUALLY\n\nuse super::types::*;\n\n",
    );
    append_global_catalog(&mut code, &global_catalog_path);
    fs::write(out_dir.join("generated.rs"), code).expect("Failed to write generated.rs");
}

fn append_global_catalog(code: &mut String, manifest_path: &Path) {
    if !manifest_path.exists() {
        code.push_str(
            "pub const PLATFORM_GLOBAL_CATALOG_METADATA: Option<RawPlatformGlobalCatalogMetadata> = None;\n",
        );
        code.push_str("pub const PLATFORM_GLOBAL_CATALOG: &[RawPlatformGlobalSymbol] = &[];\n");
        return;
    }

    let source = fs::read_to_string(manifest_path).expect("Failed to read global catalog manifest");
    let manifest: serde_json::Value =
        serde_json::from_str(&source).expect("Failed to parse global catalog manifest");
    assert_eq!(
        manifest.get("schema_version").and_then(|value| value.as_u64()),
        Some(1),
        "Unsupported global catalog schema"
    );
    let source = manifest
        .get("source")
        .and_then(|value| value.as_object())
        .expect("Global catalog source metadata is missing");
    let required = |name: &str| {
        source
            .get(name)
            .and_then(|value| value.as_str())
            .filter(|value| !value.is_empty())
            .unwrap_or_else(|| panic!("Global catalog source field {name:?} is missing"))
    };
    let platform_version = required("platform_version");
    let edt_version = required("edt_version");
    let environment_mask_bits = source
        .get("environment_mask_bits")
        .and_then(|value| value.as_object())
        .expect("Global catalog environment_mask_bits metadata is missing");
    let expected_environment_mask_bits = [
        ("thick_client", 1_u64),
        ("thin_client", 2),
        ("web_client", 4),
        ("server", 8),
        ("mobile_client", 16),
        ("external_connection", 32),
    ];
    assert_eq!(
        environment_mask_bits.len(),
        expected_environment_mask_bits.len(),
        "Global catalog environment_mask_bits contains an unknown or missing environment"
    );
    for (name, expected) in expected_environment_mask_bits {
        assert_eq!(
            environment_mask_bits.get(name).and_then(|value| value.as_u64()),
            Some(expected),
            "Global catalog environment bit for {name:?} disagrees with context_from_mask"
        );
    }
    let resources = source
        .get("resources")
        .and_then(|value| value.as_object())
        .expect("Global catalog resource provenance is missing");
    let resource_hash = |name: &str| {
        let hash = resources
            .get(name)
            .and_then(|value| value.get("sha256"))
            .and_then(|value| value.as_str())
            .unwrap_or_else(|| panic!("Global catalog resource hash {name:?} is missing"));
        assert!(
            hash.len() == 64 && hash.bytes().all(|byte| byte.is_ascii_hexdigit()),
            "Global catalog resource hash {name:?} is invalid"
        );
        hash
    };
    let global_context_sha256 = resource_hash("global_context");
    let system_enums_sha256 = resource_hash("system_enums");
    let completeness = manifest
        .get("completeness")
        .and_then(|value| value.as_object())
        .expect("Global catalog completeness metadata is missing");
    let complete_global_context =
        completeness.get("global_context").and_then(|value| value.as_bool()).unwrap_or(false);
    let complete_system_enums =
        completeness.get("system_enums").and_then(|value| value.as_bool()).unwrap_or(false);

    code.push_str("\npub const PLATFORM_GLOBAL_CATALOG_METADATA: Option<RawPlatformGlobalCatalogMetadata> = Some(RawPlatformGlobalCatalogMetadata {\n");
    code.push_str("    schema_version: 1,\n");
    code.push_str(&format!("    platform_version: {:?},\n", platform_version));
    code.push_str(&format!("    edt_version: {:?},\n", edt_version));
    code.push_str(&format!("    global_context_sha256: {:?},\n", global_context_sha256));
    code.push_str(&format!("    system_enums_sha256: {:?},\n", system_enums_sha256));
    code.push_str(&format!("    complete_global_context: {},\n", complete_global_context));
    code.push_str(&format!("    complete_system_enums: {},\n", complete_system_enums));
    code.push_str("});\n\n");

    let symbols = manifest
        .get("symbols")
        .and_then(|value| value.as_array())
        .expect("Global catalog symbols are missing");
    assert!(!symbols.is_empty(), "Attested global catalog must not be empty");
    if complete_global_context || complete_system_enums {
        let expected = manifest
            .get("attestation")
            .and_then(|value| value.get("expected_symbol_counts"))
            .and_then(|value| value.as_object())
            .expect("A complete global catalog requires independently recorded symbol counts");
        for kind in ["function", "property", "system_enum"] {
            let expected_count = expected
                .get(kind)
                .and_then(|value| value.as_u64())
                .filter(|count| *count > 0)
                .unwrap_or_else(|| panic!("Attested symbol count for {kind:?} is missing"));
            let actual_count = symbols
                .iter()
                .filter(|symbol| symbol.get("kind").and_then(|value| value.as_str()) == Some(kind))
                .count() as u64;
            assert_eq!(
                actual_count, expected_count,
                "Global catalog {kind} count does not match its attestation"
            );
        }
    }

    // `lookup()` has one deterministic winner per folded alias. Collisions are
    // safe only when every claimant has the same use capabilities: the current
    // property↔system-enum compatibility aliases are all readable/non-callable.
    // A future function↔value collision would otherwise make one valid use look
    // absent depending on manifest sort order, so reject it during the build.
    let mut alias_capabilities = std::collections::HashMap::<String, (bool, bool)>::new();
    for symbol in symbols {
        let kind = symbol.get("kind").and_then(|value| value.as_str());
        let capabilities = match kind {
            Some("function") => (true, false),
            Some("property" | "system_enum") => (false, true),
            other => panic!("Unknown global catalog symbol kind: {other:?}"),
        };
        for alias in ["ru", "en"]
            .into_iter()
            .filter_map(|field| symbol.get(field).and_then(|value| value.as_str()))
            .filter(|alias| !alias.is_empty())
        {
            let folded = alias.to_lowercase();
            if let Some(previous) = alias_capabilities.insert(folded.clone(), capabilities) {
                assert_eq!(
                    previous, capabilities,
                    "Global catalog alias {alias:?} has incompatible call/read claimants"
                );
            }
        }
    }

    code.push_str("pub const PLATFORM_GLOBAL_CATALOG: &[RawPlatformGlobalSymbol] = &[\n");
    for symbol in symbols {
        let kind = match symbol.get("kind").and_then(|value| value.as_str()) {
            Some("function") => "RawPlatformGlobalKind::Function",
            Some("property") => "RawPlatformGlobalKind::Property",
            Some("system_enum") => "RawPlatformGlobalKind::SystemEnum",
            other => panic!("Unknown global catalog symbol kind: {other:?}"),
        };
        let ru = symbol.get("ru").and_then(|value| value.as_str()).unwrap_or("");
        let en = symbol.get("en").and_then(|value| value.as_str()).unwrap_or("");
        assert!(!ru.is_empty() || !en.is_empty(), "Global catalog symbol has no alias");
        let environment_mask = symbol
            .get("environment_mask")
            .and_then(|value| value.as_u64())
            .filter(|value| *value <= u8::MAX as u64)
            .expect("Global catalog environment mask is invalid");
        let writable = symbol.get("writable").and_then(|value| value.as_bool()).unwrap_or(false);
        code.push_str("    RawPlatformGlobalSymbol {\n");
        code.push_str(&format!("        canonical_ru: {:?},\n", ru));
        code.push_str(&format!("        canonical_en: {:?},\n", en));
        code.push_str(&format!("        kind: {},\n", kind));
        code.push_str(&format!("        environment_mask: {},\n", environment_mask));
        code.push_str(&format!("        writable: {},\n", writable));
        code.push_str("    },\n");
    }
    code.push_str("];\n");
}
