[package]
name = "stdx"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
itertools.workspace = true
crossbeam-channel.workspace = true
crossbeam-utils.workspace = true
jod-thread.workspace = true
libc.workspace = true
ignore.workspace = true

[lints]
workspace = true
