[package]
name = "hir-ty"
version = "0.1.28"
edition = "2021"
authors = ["BSL Analyzer Contributors"]
license.workspace = true
repository.workspace = true

[dependencies]
cfg.workspace = true
cfg-types = { path = "../cfg-types" }
dataflow.workspace = true
hir-def = { path = "../hir-def" }
base-db = { path = "../base-db" }
bsl-config = { path = "../bsl-config" }
bsl-metadata = { path = "../bsl-metadata" }
bsl-platform = { path = "../bsl-platform" }
bsl-types.workspace = true
sdbl-hir = { path = "../sdbl-hir" }
syntax = { path = "../syntax" }
intern = { path = "../intern" }
stdx = { path = "../stdx" }
vfs = { path = "../vfs" }

salsa.workspace = true
rustc-hash.workspace = true
once_cell.workspace = true
la-arena.workspace = true
tracing.workspace = true
smol_str.workspace = true

[dev-dependencies]
expect-test = "1.5.0"
uuid = { version = "1.0", features = ["v4"] }

[lints]
workspace = true
