[package]
name = "cfg"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
petgraph = "0.8.3"
rustc-hash.workspace = true
syntax = { path = "../syntax" }
cfg-types.workspace = true
hir-def = { path = "../hir-def" }
text-size.workspace = true

[dev-dependencies]
expect-test.workspace = true
rowan.workspace = true
la-arena.workspace = true
ordered-float.workspace = true

[lints]
workspace = true
