[package]
name = "vfs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rustc-hash.workspace = true
indexmap.workspace = true
stdx.workspace = true
tracing.workspace = true
crossbeam-channel.workspace = true
paths.workspace = true

[lints]
workspace = true
