[package]
name = "ide"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bsl-conventions.workspace = true
ide-db.workspace = true
line-index.workspace = true
salsa.workspace = true
ide-diagnostics.workspace = true
ide-assists.workspace = true
hir.workspace = true
code-chunk.workspace = true
lexer.workspace = true
parser.workspace = true
syntax.workspace = true
vfs.workspace = true
stdx.workspace = true
sdbl-hir.workspace = true
bsl-metadata.workspace = true
bsl-platform.workspace = true
project-model.workspace = true
symbol-info.workspace = true
triomphe.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rayon.workspace = true
either = "1.9"
rustc-hash = "2.1"
blake3 = "1.8"
nucleo-matcher.workspace = true

[dev-dependencies]
bsl-types.workspace = true
expect-test.workspace = true
test-fixture.workspace = true
smol_str.workspace = true
tempfile.workspace = true
uuid = { version = "1.0", features = ["v4"] }

[lints]
workspace = true
